

dist: xenial

# This enables the 'defaults' to test java applications:
language: java

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/xenial/#jvm-clojure-groovy-java-scala-support
jdk:
 - openjdk8
 - openjdk11

notifications:
  email:
    recipients:
      - s.aze234@live.fr
    on_success: never # default: change
    on_failure: always # default: always
